// obtained from Wikipedia

use once_cell::sync::Lazy;
use std::collections::HashMap;

pub(crate) static LANGUAGES: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| HashMap::from([
    ("abk", "Abkhazian"),
    ("aar", "Afar"),
    ("afr", "Afrikaans"),
    ("aka", "Akan"),
    ("alb", "Albanian"),
    ("amh", "Amharic"),
    ("ara", "Arabic"),
    ("arg", "Aragonese"),
    ("arm", "Armenian"),
    ("asm", "Assamese"),
    ("ava", "Avaric"),
    ("ave", "Avestan"),
    ("aym", "Aymara"),
    ("aze", "Azerbaijani"),
    ("bam", "Bambara"),
    ("bak", "Bashkir"),
    ("baq", "Basque"),
    ("bel", "Belarusian"),
    ("ben", "Bengali"),
    ("bis", "Bislama"),
    ("bos", "Bosnian"),
    ("bre", "Breton"),
    ("bul", "Bulgarian"),
    ("bur", "Burmese"),
    ("cat", "Catalan"),
    ("cha", "Chamorro"),
    ("che", "Chechen"),
    ("nya", "Nyanja"),
    ("chi", "Chinese"),
    ("chu", "Church Slavonic"),
    ("chv", "Chuvash"),
    ("cor", "Cornish"),
    ("cos", "Corsican"),
    ("cre", "Cree"),
    ("hrv", "Croatian"),
    ("cze", "Czech"),
    ("dan", "Danish"),
    ("div", "Divehi"),
    ("dut", "Dutch"),
    ("dzo", "Dzongkha"),
    ("eng", "English"),
    ("epo", "Esperanto"),
    ("est", "Estonian"),
    ("ewe", "Ewe"),
    ("fao", "Faroese"),
    ("fij", "Fijian"),
    ("fin", "Finnish"),
    ("fre", "French"),
    ("fry", "Western Frisian"),
    ("ful", "Fulah"),
    ("gla", "Gaelic"),
    ("glg", "Galician"),
    ("lug", "Ganda"),
    ("geo", "Georgian"),
    ("ger", "German"),
    ("gre", "Greek"),
    ("kal", "Kalaallisut"),
    ("grn", "Guarani"),
    ("guj", "Gujarati"),
    ("hat", "Haitian"),
    ("hau", "Hausa"),
    ("heb", "Hebrew"),
    ("her", "Herero"),
    ("hin", "Hindi"),
    ("hmo", "Hiri Motu"),
    ("hun", "Hungarian"),
    ("ice", "Icelandic"),
    ("ido", "Ido"),
    ("ibo", "Igbo"),
    ("ind", "Indonesian"),
    ("ina", "Interlingua"),
    ("ile", "Interlingue"),
    ("iku", "Inuktitut"),
    ("ipk", "Inupiaq"),
    ("gle", "Irish"),
    ("ita", "Italian"),
    ("jpn", "Japanese"),
    ("jav", "Javanese"),
    ("kan", "Kannada"),
    ("kau", "Kanuri"),
    ("kas", "Kashmiri"),
    ("kaz", "Kazakh"),
    ("khm", "Central Khmer"),
    ("kik", "Kikuyu, Gikuyu"),
    ("kin", "Kinyarwanda"),
    ("kir", "Kirghiz, Kyrgyz"),
    ("kom", "Komi"),
    ("kon", "Kongo"),
    ("kor", "Korean"),
    ("kua", "Kuanyama, Kwanyama"),
    ("kur", "Kurdish"),
    ("lao", "Lao"),
    ("lat", "Latin"),
    ("lav", "Latvian"),
    ("lim", "Limburgan"),
    ("lin", "Lingala"),
    ("lit", "Lithuanian"),
    ("lub", "Luba-Katanga"),
    ("ltz", "Luxembourgish, Letzeburgesch"),
    ("mac", "Macedonian"),
    ("mlg", "Malagasy"),
    ("may", "Malay"),
    ("mal", "Malayalam"),
    ("mlt", "Maltese"),
    ("glv", "Manx"),
    ("mao", "Maori"),
    ("mar", "Marathi"),
    ("mah", "Marshallese"),
    ("mon", "Mongolian"),
    ("nau", "Nauru"),
    ("nav", "Navajo, Navaho"),
    ("nde", "North Ndebele"),
    ("nbl", "South Ndebele"),
    ("ndo", "Ndonga"),
    ("nep", "Nepali"),
    ("nor", "Norwegian"),
    ("nob", "Norwegian Bokmål"),
    ("nno", "Norwegian Nynorsk"),
    ("iii", "Sichuan Yi, Nuosu"),
    ("oci", "Occitan"),
    ("oji", "Ojibwa"),
    ("ori", "Oriya"),
    ("orm", "Oromo"),
    ("oss", "Ossetian"),
    ("pli", "Pali"),
    ("pus", "Pashto"),
    ("per", "Persian"),
    ("pol", "Polish"),
    ("por", "Portuguese"),
    ("pan", "Punjabi"),
    ("que", "Quechua"),
    ("rum", "Romanian"),
    ("roh", "Romansh"),
    ("run", "Rundi"),
    ("rus", "Russian"),
    ("sme", "Northern Sami"),
    ("smo", "Samoan"),
    ("sag", "Sango"),
    ("san", "Sanskrit"),
    ("srd", "Sardinian"),
    ("srp", "Serbian"),
    ("sna", "Shona"),
    ("snd", "Sindhi"),
    ("sin", "Sinhala, Sinhalese"),
    ("slo", "Slovak"),
    ("slv", "Slovenian"),
    ("som", "Somali"),
    ("sot", "Southern Sotho"),
    ("spa", "Spanish"),
    ("sun", "Sundanese"),
    ("swa", "Swahili"),
    ("ssw", "Swati"),
    ("swe", "Swedish"),
    ("tgl", "Tagalog"),
    ("tah", "Tahitian"),
    ("tgk", "Tajik"),
    ("tam", "Tamil"),
    ("tat", "Tatar"),
    ("tel", "Telugu"),
    ("tha", "Thai"),
    ("tib", "Tibetan"),
    ("tir", "Tigrinya"),
    ("ton", "Tonga (Tonga Islands)"),
    ("tso", "Tsonga"),
    ("tsn", "Tswana"),
    ("tur", "Turkish"),
    ("tuk", "Turkmen"),
    ("twi", "Twi"),
    ("uig", "Uyghur"),
    ("ukr", "Ukrainian"),
    ("urd", "Urdu"),
    ("uzb", "Uzbek"),
    ("ven", "Venda"),
    ("vie", "Vietnamese"),
    ("vol", "Volapük"),
    ("wln", "Walloon"),
    ("wel", "Welsh"),
    ("wol", "Wolof"),
    ("xho", "Xhosa"),
    ("yid", "Yiddish"),
    ("yor", "Yoruba"),
    ("zha", "Zhuang"),
    ("zul", "Zulu"),
]));
